#!/usr/bin/env python3

# rdserialtool
# Copyright (C) 2019 Ryan Finnie
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

import json
import os

def response_callback(response):
    json_file = os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])), 'charge.json')
    print(json_file)
    history = []
    try:
        with open(json_file, 'r') as file:
            history = json.load(file)
    except IOError:
        pass
    history.append(json.loads(response))
    with open(json_file, 'w') as file:
        json.dump(history, file)

def get_config():
    json_file = os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])), 'config.json')
    try:
        with open(json_file, 'r') as file:
            return json.load(file)
    except IOError as ioerror:
        print(f'Error reading config: {ioerror}', file=sys.stderr)
        return {}
if __name__ == '__main__':
    import sys
    import rdserial.tool
    config = get_config()
    sys.exit(rdserial.tool.main(callback=response_callback,
                                **config))
